package dto;
// Generated 26 mars 2021 ï¿½ 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "evaly")
public class QuestionDto implements java.io.Serializable {

	private Integer idQuestion;
	private Integer theme;
	
	private Integer idMatiere;
	private String nvtheme;
	private String nvthemebool;

	private String descriptionQuestion;
	private Integer coefficient;
	private Boolean isQcm;
	private double tauxreussite;
	private Integer nbnotes;
	private String rep1;
	private String rep2;
	private String rep3;
	private String rep4;
	private String rep1br;
	private String rep2br;
	private String rep3br;
	private String rep4br;
	private Boolean isVrai;
	private Boolean toReset;

	public QuestionDto() {
	}

	public String getNvthemebool() {
		return nvthemebool;
	}

	public void setNvthemebool(String nvthemebool) {
		this.nvthemebool = nvthemebool;
	}
	
	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}
	
	public Integer getTheme() {
		return this.theme;
	}

	public void setTheme(Integer theme) {
		this.theme = theme;
	}

	public String getDescriptionQuestion() {
		return this.descriptionQuestion;
	}

	public void setDescriptionQuestion(String descriptionQuestion) {
		this.descriptionQuestion = descriptionQuestion;
	}

	public Integer getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Integer coefficient) {
		this.coefficient = coefficient;
	}

	public Boolean getIsQcm() {
		return this.isQcm;
	}

	public void setIsQcm(Boolean isQcm) {
		this.isQcm = isQcm;
	}


	public double getTauxreussite() {
		return tauxreussite;
	}

	public void setTauxreussite(double tauxreussite) {
		this.tauxreussite = tauxreussite;
	}

	
	public Integer getNbnotes() {
		return nbnotes;
	}

	public void setNbnotes(Integer nbnotes) {
		this.nbnotes = nbnotes;
	}

	public String getRep1() {
		return rep1;
	}

	public void setRep1(String rep1) {
		this.rep1 = rep1;
	}

	public String getRep2() {
		return rep2;
	}

	public void setRep2(String rep2) {
		this.rep2 = rep2;
	}

	public String getRep3() {
		return rep3;
	}

	public void setRep3(String rep3) {
		this.rep3 = rep3;
	}

	public String getRep4() {
		return rep4;
	}

	public void setRep4(String rep4) {
		this.rep4 = rep4;
	}

	public Boolean getIsVrai() {
		return isVrai;
	}

	public void setIsVrai(Boolean isVrai) {
		this.isVrai = isVrai;
	}



	public Integer getIdMatiere() {
		return idMatiere;
	}

	public void setIdMatiere(Integer idMatiere) {
		this.idMatiere = idMatiere;
	}

	public String getNvtheme() {
		return nvtheme;
	}

	public void setNvtheme(String nvtheme) {
		this.nvtheme = nvtheme;
	}

	public String getRep1br() {
		return rep1br;
	}

	public void setRep1br(String rep1br) {
		this.rep1br = rep1br;
	}

	public String getRep2br() {
		return rep2br;
	}

	public void setRep2br(String rep2br) {
		this.rep2br = rep2br;
	}

	public String getRep3br() {
		return rep3br;
	}

	public void setRep3br(String rep3br) {
		this.rep3br = rep3br;
	}

	public String getRep4br() {
		return rep4br;
	}

	public void setRep4br(String rep4br) {
		this.rep4br = rep4br;
	}

	public Boolean getToReset() {
		return toReset;
	}

	public void setToReset(Boolean toReset) {
		this.toReset = toReset;
	}


	
	
	

}