package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApprenantId generated by hbm2java
 */
@Embeddable
public class ApprenantId implements java.io.Serializable {

	private int idUtilisateur;
	private Integer idPromotion;

	public ApprenantId() {
	}

	public ApprenantId(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public ApprenantId(int idUtilisateur, Integer idPromotion) {
		this.idUtilisateur = idUtilisateur;
		this.idPromotion = idPromotion;
	}

	@Column(name = "id_utilisateur", nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "id_promotion")
	public Integer getIdPromotion() {
		return this.idPromotion;
	}

	public void setIdPromotion(Integer idPromotion) {
		this.idPromotion = idPromotion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApprenantId))
			return false;
		ApprenantId castOther = (ApprenantId) other;

		return (this.getIdUtilisateur() == castOther.getIdUtilisateur())
				&& ((this.getIdPromotion() == castOther.getIdPromotion())
						|| (this.getIdPromotion() != null && castOther.getIdPromotion() != null
								&& this.getIdPromotion().equals(castOther.getIdPromotion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUtilisateur();
		result = 37 * result + (getIdPromotion() == null ? 0 : this.getIdPromotion().hashCode());
		return result;
	}

}
