package model;
// Generated 26 mars 2021 � 22:40:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormateurId generated by hbm2java
 */
@Embeddable
public class FormateurId implements java.io.Serializable {

	private int idUtilisateur;
	private Boolean isReferent;

	public FormateurId() {
	}

	public FormateurId(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public FormateurId(int idUtilisateur, Boolean isReferent) {
		this.idUtilisateur = idUtilisateur;
		this.isReferent = isReferent;
	}

	@Column(name = "id_utilisateur", nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "is_referent")
	public Boolean getIsReferent() {
		return this.isReferent;
	}

	public void setIsReferent(Boolean isReferent) {
		this.isReferent = isReferent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormateurId))
			return false;
		FormateurId castOther = (FormateurId) other;

		return (this.getIdUtilisateur() == castOther.getIdUtilisateur())
				&& ((this.getIsReferent() == castOther.getIsReferent())
						|| (this.getIsReferent() != null && castOther.getIsReferent() != null
								&& this.getIsReferent().equals(castOther.getIsReferent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUtilisateur();
		result = 37 * result + (getIsReferent() == null ? 0 : this.getIsReferent().hashCode());
		return result;
	}

}
